package com.csinfotechbd.collection.settings.dealerGroupBasedOnCollectorAreaForAutoDistribution;

import com.csinfotechbd.common.CommonRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface DealerGroupBasedOnCollectorAreaForAutoDistributionRepository extends CommonRepository<DealerGroupBasedOnCollectorAreaForAutoDistribution> {
}
